### PR TITLE
Multi-engine Support

### LINKED ISSUE #33: Add Support for the KV V2 Secrets Engine
### Design considerations:
- Vault has many secret engines, and will likely have more in the future. This means the client should be as extensible as possible to support each of these operations
- Using these operations should be as simple as possible
- The entire enhancement can be done without breaking backwards compatibility

### Proposed implementation:

1. From common functions shared by all secret engines (eg. CRUD operations on secrets), call multi-methods that dispatch based on the secret engine type. If the secret engine is not inputted, default to the generic secret engine operations (current behavior).
2. Add additional functions to the http client and mock client to support the KV V2 API
3. Expose additional functions in a kv-mount protocol. This protocol will either be in the `vault.core` namespace or in its own namespace. Here’s a breakdown of the arguments for both options:
    - `vault.core` already contains all the other exposed functions. It’s an easy go to file to read up on what functions an end user should call. This may be harder to use as the client adds support for more secret engines over time since functions are not separated into their own namespaces. For example, `read-metadata` is an operation that cannot be called on a `generic` secret engine. This concern could be largely ameliorated by a clear naming strategy (eg. prefixing all kv v2 specific functions with kv)
    - A custom namespace would allow users to know exactly what functions correspond with kv mounts. Usage would be along the lines of `(kv-mount/read-metadata <PATH>)`. This has a few benefits. First, autocomplete in any editor will give you a much shorter list of possible operations to look through (no matter how many secret engines are supported). Second,  it becomes much harder for an end user to accidentally use the wrong method because it’s much more explicit. Finally, it won’t balloon the size of `vault.core` as new engines are added. However, this is in many ways less discoverable than adding the protocol to `vault.core`. There would no longer be a centralized place to see all possible client operations, so users may not know an operation is available.

### PR DESCRIPTION
**Pull request by drassaby**
Resolves #35 

### What is currently in this PR?
From a sorta stack trace perspective, the work is like this:
1. User calls a function (eg. `read-secret`) in a secret namespace, which uses the input params to change the request into a (or a series of) logical read/write/list/delete requests
2. Those read/write/list/delete requests are performed by the secret client
3. From here there are two options depending on the secret client:
    - Mock Client -- works as before, returning a mocked response
    - HTTP Client -- works as before, sending the requests to Vault

vault-clj multi-engine support danny v1

This drawing can be copied at: https://docs.google.com/drawings/d/1M_0S5RrTHA5IWYJeYOWAlL2O5sfZp_WOnGUtEJyhqA4/edit?usp=sharing

#### Other details
- This PR also implements a few of the core functions for the `kvv2` secret engine. It does not implement all of them, further functions will be implemented in a later PR.
- Code was further refactored to remove as much as possible from the `http-client` code. Authenticate and lease operations were moved to their respective namespaces.
- Bugfix for mocking delete using kvv1

#### Seperate secret engine namespacing makes end user usage (arguably) easier
See #33 for a more in depth discussion of this.

#### Code structure
The `vault.client.http` client is already way too big, this allows the code to grow in files outside of the http client

#### Mock clients work as before
Mocking is so nice with `vault-clj` since we can easily mock the client as opposed to each individual method. This implementation maintains that, and will support any secret engine that breaks down it's requests in the style described in the image above.

#### Backwards-Compatible
While users should switch over to the new style, this change is backwards compatible.

#### Extensibility
A lot of secret engines have operations that are unique to those secret engines. Every time a new operation is added, only the new namespace for that engine has to be edited. This means that supported secret engines **do not** have to be written into `vault-clj` itself instead of some form of plugin or *extension* (like we do with [AWS Auth for `vault-clj`](https://github.com/amperity/vault-clj-aws))

#### Mocking is only supported if the above style of secret engine is implemented
That's a bullet we have to bite I think. Given that style of secret engine is pretty simple to implement anyway, a good addition to the README can explain this

### Other Considerations and TODOs
- [x] Add documentation to README about how best to use secret engines. Also, how to add new secret engines
- [x] Test Mock client
- [x] This implementation is not yet complete, but if we want to move forward with it, then we should separate more things into their own namespaces (like authenticate, etc.)
- [x] Add docstrings for all functions in Secret Engines

### CODE REVIEW

**Comment by drassaby** [comment]
> I suggest avoiding multimethods altogether.
> 
> If the mock client only implemented basically the old SecretClient protocol, what you refer to as the "logical" secret engine:
> 
> ```clojure
> (defprotocol Logical
>   (read [this path opts])
>   (list [this path opts])
>   (write [this path data opts])
>   (delete [this path opts]))
> ```
> 
> and each secret engine made use of these primitive functions directly, multimethods wouldn't be necessary. Each engine would implementing their own set of functions in their own namespaces. Browsing through the list of secret engines, no significant set of common methods jumped out to me, so implementing each secret engine individually gives you more freedom to be useful in a way specific to that engine itself instead of trying to shoehorn into a common interface. It also still allows maintaining a simple mock client, which is nice!
> 
> This extension model (as much as it is one) lets each implementation of a secret engine exist as a namespace, which could live in this project or another one.
> 
> Otherwise, I have some observational comments as I browsed through, but some are unecessary or moot if the above is followed. Just wanted to mention some of them anyway since they are more general to clojure itself vs this project.

This is super helpful! Thanks @pyncc, I will go back and modify it to work like this :) Definitely addresses my concerns with extensibility and complexity, and gets rid of the repetitive (+ ugly haha) code structure to route through the client

File: src/vault/secrets/dispatch.clj [hunk 1]
```diff
@@ -0,0 +1,63 @@
+; Handles dispatch related to the functions from the secret engines protocol
```
[the remark this answers is not in the document]
Comment (drassaby) [reply src/vault/secrets/dispatch.clj]: Good to know! Deleted that `ns` now, but will start doing that when I make new ones

File: src/vault/secrets/kvv2.clj [hunk 2]
```diff
@@ -0,0 +1,69 @@
+(ns vault.secrets.kvv2
+  (:require
+    [clojure.tools.logging :as log]
+    [vault.client.http :as http-client]
+    [vault.secret-engines :as engine]
+    [vault.secrets.dispatch :refer [read-secret* write-secret!* write-config!* read-config*]]
```
[the remark this answers is not in the document]
Comment (drassaby) [reply src/vault/secrets/kvv2.clj]: Definitely agreed

File: test/vault/secrets/kvv2_test.clj [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+        client (vault.core/new-client vault-url)
+        new-config {:max_versions 5
+                    :cas_require false
+                    :delete_version_after "3h25m19s"}]
+    (vault.core/authenticate! client :token token-passed-in)
+    (testing "Config can be updated with valid call"
+      (with-redefs
+        [clj-http.client/request
+         (fn [req]
+           (is (= :post (:method req)))
```
[the remark this answers is not in the document]
Comment (drassaby) [reply test/vault/secrets/kvv2_test.clj]: I tried to make it as as agnostic as possible to the internal implementation, which is why I mocked  at the http request level, and wrote these against the Vault API as opposed to against the code. For any `write` or `delete` especially, these are arguably the most important tests (testing the structure of the request). Do you have any suggestions on other ways to test this?

We could inject the http client into the vault client, and then I could create a mock one that allows me to set up similar assertions? But that seems just as brittle

I could use something like this: https://github.com/myfreeweb/clj-http-fake
But it just use redefs under the hood like I did here, and I still would want to assert on the structure of the request which it doesn't really help with

File: src/vault/core.clj [hunk 4]
```diff
@@ -131,6 +131,44 @@
     "Removes the watch function registered with the given key, if any."))
 
 
+(defprotocol SecretEngine
+  "Basic API for listing, reading, and writing secrets.
+
+  `eng` is a keyword representing the secret engine/mount"
```
Comment (pyncc) [inline src/vault/core.clj]: missed deleting this. if possible reverting one of the old commits would be nicer but if it wasn't factored out cleanly no worries.

File: test/vault/secrets/kvv2_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (pyncc) [reply test/vault/secrets/kvv2_test.clj]: I guess I'm not sure why a kvv2 unit test should care specifically about the client implementation, this seems like a boundary-crossing thing. If it were an integration or functional test (and was marked with metadata as such so it could be run separately) I could see testing this end-to-end like that.

Otherwise, the unit test should be testing (externally known) state before and after a transition such as `write-config!`.

[the remark this answers is not in the document]
Comment (drassaby) [reply test/vault/secrets/kvv2_test.clj]: I wouldn't really call this an integration test since I'm not actually running a vault server, but it definitely is a functional test. But I think functional testing and unit testing for publicly exposed functions sometimes overlap, as in this case. I'm also not sure it matters how it's labelled, since it's a fast test that should be run by CI after every change anyway.

I don't really think it's possible to meaningfully test a CLI that exposes an HTTP API without checking the requests being sent to the API endpoint are valid. No matter how I test it, I will have to mock the http request. So the question is whether that mock includes assertions on the data passed to it. This is not really an internal implementation detail (except for the fact that we need to know that `clj-http` is being used), since the format of the request is implementation agnostic (in fact these tests were written prior to writing the code, and the implementation has changed significantly since the tests were written without having to rewrite them)

File: src/vault/core.clj (hunk 4 above)
Comment (drassaby) [reply src/vault/core.clj]: I moved it back to `Core` and deleted the other file/ns I made for it. I'm not worried about the ballooning issue now

Comment (drassaby) [reply src/vault/core.clj]: Agree, but it was part of a larger commit :/

File: test/vault/secrets/logical_test.clj [hunk 5]
```diff
@@ -0,0 +1,108 @@
+(ns vault.secrets.logical-test
+  (:require
+    [clojure.test :refer [is testing deftest]]
+    [vault.client.http]
+    [vault.secrets.logical :as vault-logical])
```
Comment (pyncc) [inline test/vault/secrets/logical_test.clj]: Now that the basic "secret client" protocol is implemented by the clients, i think this "logical" secrets engine should be renamed "kvv1" to match actually naming in vault.

File: test/vault/secrets/kvv2_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (pyncc) [reply test/vault/secrets/kvv2_test.clj]: I see what you're saying in terms of needing to test against a known http endpoint: this should confirm it meets the contract of what that endpoint is expecting. I am probably just getting hung up on naming and semantics not so much arguing about the validity of this kind of testing.

The test says (from the `testing` form above): "Config can be updated with valid call", yet is not testing that portion of the contract or behavior since the http request returns a blank `:status 200`.

It is testing "can an authenticated http client form a correct request to write a secret to kvv2". Not trying to be prescriptive of naming here, trying to point out what these tests are actually trying to accomplish should match stated goals. I think it would sit better with me if the intent of the test is more clear in naming, description.

As I look around more, this description matching reality is generally true (eg https://github.com/amperity/vault-clj/pull/35/files/d373794059e28d008a50fef7f3cca91185e0033c#diff-be1f5f4507061b33600be2eea08d1651R85), I guess I've just narrowly noticed this, and its a fairly minor detail to fix.

> the format of the request is implementation agnostic (in fact these tests were written prior to writing the code, and the implementation has changed significantly since the tests were written without having to rewrite them)

this seems like a nice signal that these assertion then are not brittle, sounds good!

File: test/vault/secrets/kvv2_test.clj [hunk 6]
```diff
@@ -0,0 +1,133 @@
+(ns vault.secrets.kvv2-test
```
Comment (pyncc) [inline test/vault/secrets/kvv2_test.clj]: In addition to the comment below about intent, I think my objections about testing http-client interaction from this test ns would go away more if there was a test of the secret engine itself, using the mock client. Pretty basic unit tests, but just asserting create, read, list, delete work as expected.

File: test/vault/secrets/logical_test.clj (hunk 5 above)
Comment (drassaby) [reply test/vault/secrets/logical_test.clj]: Good point :) agreed

File: test/vault/secrets/kvv2_test.clj (hunk 3 above)
[the remark this answers is not in the document]
Comment (drassaby) [reply test/vault/secrets/kvv2_test.clj]: > It is testing "can an authenticated http client form a correct request to write a secret to kvv2". Not trying to be prescriptive of naming here, trying to point out what these tests are actually trying to accomplish should match stated goals. I think it would sit better with me if the intent of the test is more clear in naming, description.

That's a good point! I'll make the naming more descriptive, the description currently makes it sound more like an integration test than it is

File: test/vault/secrets/kvv2_test.clj (hunk 6 above)
Comment (drassaby) [reply test/vault/secrets/kvv2_test.clj]: Agreed, definitely going to test the mock client like you're suggesting, measuring known external state through client interactions (eg. write a secret, then read it back, etc.)

File: src/vault/api_util.clj [hunk 7]
```diff
@@ -0,0 +1,129 @@
...
+                 (catch Exception ex
+                   (throw (api-error ex))))]
+      (if-let [location (and (#{303 307} (:status resp))
+                             (get-in resp [:headers "Location"]))]
+        (do (log/debug "Retrying API request redirected to " location)
+            (recur method location (assoc req ::redirects (inc redirects))))
+        resp))))
+
+
+(defn ^:no-doc api-request
```
Comment (pyncc) [inline src/vault/api_util.clj]: I started out reading the code thinking this shouldn't be hidden, but now that I think of it more, it makes sense that no code except the http-client should be using this anyway, so it should be obscured for better understanding of usage.

File: src/vault/api_util.clj [hunk 8]
```diff
@@ -0,0 +1,129 @@
+(ns vault.api-util
```
Comment (pyncc) [inline src/vault/api_util.clj]: Is there a rationale for not putting this under the client namespace? 
I think organisation and dependency would be more clear if it lived at: `src/vault/client/api_util.clj`

This is especially true when its primarily a set of subroutines only used by `amperity.client.http`.

File: README.md [hunk 9]
```diff
@@ -57,10 +60,48 @@ secret fixture data.
...
+(require '[vault.secrets.kvv1 :as kvv1])
+```
+
+#### [KV V2](https://www.vaultproject.io/docs/secrets/kv/kv-v2.html)
+
+```clojure
+(require '[vault.secrets.kvv2 :as kvv2])
+```
+
+### Adding your own Secret Engines
```
[the remark this answers is not in the document]
Comment (drassaby) [reply README.md]: Thanks!

File: src/vault/api_util.clj (hunk 8 above)
Comment (drassaby) [reply src/vault/api_util.clj]: You're right, I think that'd be cleaner. I'll move it!

File: src/vault/api_util.clj (hunk 7 above)
Comment (drassaby) [reply src/vault/api_util.clj]: Yeah :) mainly just trying to get people to send requests through the `http-client` if they write their own secret engines

File: src/vault/lease.clj [hunk 10]
```diff
@@ -166,3 +168,52 @@
       (when (not= (:lease-id old-info)
                   (:lease-id new-info))
         (watch-fn new-info)))))
+
+;; Larger scale lease logic
```
[the remark this answers is not in the document]
Comment (drassaby) [reply src/vault/lease.clj]: Yeah, I'll make the comment more explicit. Or maybe just remove it. At least as written now, it adds more confusion than clarification
